[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"
authors = ["Zacbary Conger <zachary@econger.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
